import { defineConfig } from 'vite'
import { fileURLToPath } from 'url'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'

/**
 * Library build configuration.
 * Run via: npm run build:lib
 *
 * Outputs:
 *   dist/index.js   — ESM bundle (tree-shakeable)
 *   dist/index.css  — Tailwind-generated stylesheet (consumers must import separately)
 *   dist/index.d.ts — TypeScript declarations (generated by tsc, see tsconfig.build.json)
 */
const root = fileURLToPath(new URL('.', import.meta.url))

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      '@': `${root}src`,
    },
  },
  build: {
    lib: {
      entry: `${root}src/app/components/openapi-designer/index.ts`,
      name: 'OpenAPIDesigner',
      formats: ['es'],
      fileName: 'index',
    },
    rollupOptions: {
      // React must be provided by the consumer (peer dependency).
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      output: {
        // Write CSS asset as dist/index.css so the exports map resolves correctly.
        assetFileNames: 'index.[ext]',
      },
    },
    outDir: 'dist',
    emptyOutDir: true,
    sourcemap: true,
    // Emit a single CSS file instead of per-chunk splits.
    cssCodeSplit: false,
  },
})
